//! Regression test for GEN002: plugin-generated functions with double-underscore
//! prefix (e.g. `__redirect_0` from `expand_block("routes")`) must be exported
//! from the WASM module so the server runtime can dispatch to them by name.
//!
//! Root cause (v0.30.218): The export loop in `finalize_module` skipped
//! double-underscore functions unless they matched `__route_handler_N` or
//! `__page_handler_*`.  Functions generated by plugins (preamble expansion)
//! such as `__redirect_0` were compiled but never exported, causing the server
//! to fail with "Could not find or call handler '__redirect_0'".
//!
//! Fix: Added `user_defined_function_names` to `MirCodeGenerator`.  Every
//! function from `mir_program.functions` is tracked there during
//! pre-registration and is always exported regardless of underscore prefix.
//! Internal compiler helpers (`__malloc`, `__string_concat`, etc.) are NOT in
//! this set because they are registered via `register_function`, not from
//! `mir_program.functions`.

use clean_language_compiler::codegen::mir_codegen::MirCodeGenerator;
use clean_language_compiler::mir::mir_types::{
    BasicBlockId, MirBasicBlock, MirFunction, MirFunctionAttributes, MirProgram, MirTerminator,
    MirType,
};
use clean_language_compiler::resolver::SymbolId;
use std::collections::{BTreeMap, HashMap};
use wasmparser::{Parser as WasmParser, Payload};

/// Build a minimal MirProgram containing a single void function with the given
/// name and a `start` entry point that calls it.
fn build_program_with_function(func_name: &str) -> MirProgram {
    use clean_language_compiler::mir::mir_types::{MirInstruction, MirOperand, MirOperation};

    // SymbolId 5000 = the plugin-generated handler function (e.g. __redirect_0)
    let handler_symbol = SymbolId(5000);
    // SymbolId 5001 = the start/entry function
    let start_symbol = SymbolId(5001);

    // Build the handler function: void __redirect_0() { return; }
    let handler_block_id = BasicBlockId(0);
    let handler_block = MirBasicBlock {
        id: handler_block_id,
        label: None,
        instructions: vec![],
        terminator: MirTerminator::Return { value: None },
        predecessors: Default::default(),
        successors: Default::default(),
        location: Default::default(),
    };
    let handler_fn = MirFunction {
        symbol_id: handler_symbol,
        name: func_name.to_string(),
        parameters: vec![],
        return_type: MirType::Void,
        blocks: {
            let mut m = HashMap::new();
            m.insert(handler_block_id, handler_block);
            m
        },
        entry_block: handler_block_id,
        locals: HashMap::new(),
        next_value_id: 0,
        next_block_id: 1,
        attributes: MirFunctionAttributes {
            inline: false,
            pure: false,
            entry_point: false,
            exported: true,
        },
        location: Default::default(),
    };

    // Build the start function: void start() { __redirect_0(); return; }
    // We call the handler so the reference is exercised (not strictly needed
    // for the export test, but mirrors real plugin-generated code).
    let start_block_id = BasicBlockId(0);
    let call_instr = MirInstruction {
        dest: None,
        operation: MirOperation::Call {
            function: MirOperand::Function(handler_symbol),
            arguments: vec![],
        },
        location: Default::default(),
    };
    let start_block = MirBasicBlock {
        id: start_block_id,
        label: None,
        instructions: vec![call_instr],
        terminator: MirTerminator::Return { value: None },
        predecessors: Default::default(),
        successors: Default::default(),
        location: Default::default(),
    };
    let start_fn = MirFunction {
        symbol_id: start_symbol,
        name: "start".to_string(),
        parameters: vec![],
        return_type: MirType::Void,
        blocks: {
            let mut m = HashMap::new();
            m.insert(start_block_id, start_block);
            m
        },
        entry_block: start_block_id,
        locals: HashMap::new(),
        next_value_id: 0,
        next_block_id: 1,
        attributes: MirFunctionAttributes {
            inline: false,
            pure: false,
            entry_point: true,
            exported: true,
        },
        location: Default::default(),
    };

    let mut functions = BTreeMap::new();
    functions.insert(handler_symbol, handler_fn);
    functions.insert(start_symbol, start_fn);

    let mut symbol_name_map = BTreeMap::new();
    symbol_name_map.insert(handler_symbol, func_name.to_string());
    symbol_name_map.insert(start_symbol, "start".to_string());

    MirProgram {
        functions,
        globals: BTreeMap::new(),
        string_pool: vec![],
        entry_point: Some(start_symbol),
        debug_info: None,
        symbol_name_map,
        used_plugins: vec![],
        state_rules: vec![],
        state_guards: vec![],
        externals: vec![],
        test_functions: vec![],
        class_ids: BTreeMap::new(),
        capability_dispatch: BTreeMap::new(),
    }
}

/// Parse the export section of a WASM binary and return the set of exported
/// function names.
fn exported_function_names(wasm_bytes: &[u8]) -> std::collections::HashSet<String> {
    let mut names = std::collections::HashSet::new();
    for payload in WasmParser::new(0).parse_all(wasm_bytes) {
        if let Ok(Payload::ExportSection(reader)) = payload {
            for export in reader {
                let export = export.expect("valid export entry");
                if matches!(export.kind, wasmparser::ExternalKind::Func) {
                    names.insert(export.name.to_string());
                }
            }
        }
    }
    names
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

/// GEN002 — core case: a function whose name begins with `__` but is present
/// in `mir_program.functions` (plugin-generated) must appear in the WASM
/// export table.
#[test]
fn gen002_double_underscore_function_is_exported() {
    let func_name = "__redirect_0";
    let mir_program = build_program_with_function(func_name);

    let mut codegen = MirCodeGenerator::new();
    let result = codegen.generate(mir_program).expect("codegen must succeed");

    let exports = exported_function_names(&result.wasm_bytes);

    assert!(
        exports.contains(func_name),
        "GEN002: '{}' must be exported but was not found in WASM exports.\n\
         Actual exports: {:?}",
        func_name,
        exports
    );
}

/// GEN002 — additional case: a regular user function is still exported
/// (no regression from the GEN002 fix).
#[test]
fn gen002_regular_function_still_exported() {
    let func_name = "myHandler";
    let mir_program = build_program_with_function(func_name);

    let mut codegen = MirCodeGenerator::new();
    let result = codegen.generate(mir_program).expect("codegen must succeed");

    let exports = exported_function_names(&result.wasm_bytes);

    assert!(
        exports.contains(func_name),
        "Regular user function '{}' must be exported but was not found.\n\
         Actual exports: {:?}",
        func_name,
        exports
    );
}

/// GEN002 — additional case: a single-underscore callback function is still
/// exported (no regression from the GEN002 fix).
#[test]
fn gen002_single_underscore_callback_still_exported() {
    let func_name = "_frame_callback";
    let mir_program = build_program_with_function(func_name);

    let mut codegen = MirCodeGenerator::new();
    let result = codegen.generate(mir_program).expect("codegen must succeed");

    let exports = exported_function_names(&result.wasm_bytes);

    assert!(
        exports.contains(func_name),
        "Single-underscore callback '{}' must be exported but was not found.\n\
         Actual exports: {:?}",
        func_name,
        exports
    );
}

/// GEN002 — root-cause regression (v0.30.221): two MirFunction entries with the
/// same name but different SymbolIds must not corrupt the export table.
///
/// Trigger: plugin preamble injection on the entry module re-emits helpers
/// (e.g. `__redirect_0`) that a non-entry module already generated via block
/// expansion.  Before the fix the second insert into `function_map` overwrote
/// the first, orphaning the function body and silently dropping its export.
#[test]
fn gen002_duplicate_symbol_ids_same_name_exports_exactly_once() {
    use clean_language_compiler::mir::mir_types::{MirInstruction, MirOperand, MirOperation};

    let func_name = "__redirect_0";
    // Two different SymbolIds for the same function name (simulates the
    // preamble-injection duplication across compilation units).
    let sym_a = SymbolId(100); // from routes.cln expansion
    let sym_b = SymbolId(200); // from main.cln preamble injection
    let start_sym = SymbolId(300);

    let make_void_fn = |sym: SymbolId, name: &str| -> MirFunction {
        let block_id = BasicBlockId(0);
        let block = MirBasicBlock {
            id: block_id,
            label: None,
            instructions: vec![],
            terminator: MirTerminator::Return { value: None },
            predecessors: Default::default(),
            successors: Default::default(),
            location: Default::default(),
        };
        MirFunction {
            symbol_id: sym,
            name: name.to_string(),
            parameters: vec![],
            return_type: MirType::Void,
            blocks: {
                let mut m = HashMap::new();
                m.insert(block_id, block);
                m
            },
            entry_block: block_id,
            locals: HashMap::new(),
            next_value_id: 0,
            next_block_id: 1,
            attributes: MirFunctionAttributes {
                inline: false,
                pure: false,
                entry_point: false,
                exported: true,
            },
            location: Default::default(),
        }
    };

    // Both duplicates have the same name — codegen must de-duplicate, keeping
    // the first (lowest SymbolId) and emitting only one WASM function + export.
    let fn_a = make_void_fn(sym_a, func_name);
    let fn_b = make_void_fn(sym_b, func_name);

    // Build a start function that calls sym_a (the kept copy)
    let start_block_id = BasicBlockId(0);
    let call_instr = MirInstruction {
        dest: None,
        operation: MirOperation::Call {
            function: MirOperand::Function(sym_a),
            arguments: vec![],
        },
        location: Default::default(),
    };
    let start_block = MirBasicBlock {
        id: start_block_id,
        label: None,
        instructions: vec![call_instr],
        terminator: MirTerminator::Return { value: None },
        predecessors: Default::default(),
        successors: Default::default(),
        location: Default::default(),
    };
    let start_fn = MirFunction {
        symbol_id: start_sym,
        name: "start".to_string(),
        parameters: vec![],
        return_type: MirType::Void,
        blocks: {
            let mut m = HashMap::new();
            m.insert(start_block_id, start_block);
            m
        },
        entry_block: start_block_id,
        locals: HashMap::new(),
        next_value_id: 0,
        next_block_id: 1,
        attributes: MirFunctionAttributes {
            inline: false,
            pure: false,
            entry_point: true,
            exported: true,
        },
        location: Default::default(),
    };

    let mut functions = BTreeMap::new();
    functions.insert(sym_a, fn_a);
    functions.insert(sym_b, fn_b); // duplicate name — must be silently dropped
    functions.insert(start_sym, start_fn);

    let mut symbol_name_map = BTreeMap::new();
    symbol_name_map.insert(sym_a, func_name.to_string());
    symbol_name_map.insert(sym_b, func_name.to_string());
    symbol_name_map.insert(start_sym, "start".to_string());

    let mir_program = MirProgram {
        functions,
        globals: BTreeMap::new(),
        string_pool: vec![],
        entry_point: Some(start_sym),
        debug_info: None,
        symbol_name_map,
        used_plugins: vec![],
        state_rules: vec![],
        state_guards: vec![],
        externals: vec![],
        test_functions: vec![],
        class_ids: BTreeMap::new(),
        capability_dispatch: BTreeMap::new(),
    };

    let mut codegen = MirCodeGenerator::new();
    let result = codegen
        .generate(mir_program)
        .expect("codegen must not fail with duplicate names");

    let exports = exported_function_names(&result.wasm_bytes);

    assert!(
        exports.contains(func_name),
        "GEN002: '{}' must be exported even when two SymbolIds share the same name.\n\
         Actual exports: {:?}",
        func_name,
        exports
    );

    let count = exports.iter().filter(|n| n.as_str() == func_name).count();
    assert_eq!(
        count, 1,
        "GEN002: '{}' must appear exactly once in the export table, found {}.\n\
         Actual exports: {:?}",
        func_name, count, exports
    );
}

/// GEN002 — verify that compiler-internal helpers (__malloc, __string_concat,
/// etc.) are NOT exported when they are NOT in mir_program.functions.
/// They are registered via register_function() and should remain unexported.
#[test]
fn gen002_internal_helpers_not_exported() {
    // Build a minimal program that exercises the code path requiring __malloc
    // (a string concatenation would trigger it, but for this test a simple
    // void start is enough — we just want to check that __malloc is not
    // accidentally exported).
    let mir_program = build_program_with_function("__redirect_0");

    let mut codegen = MirCodeGenerator::new();
    let result = codegen.generate(mir_program).expect("codegen must succeed");

    let exports = exported_function_names(&result.wasm_bytes);

    // __malloc is an internal helper registered via register_function(),
    // NOT via mir_program.functions, so it must not be exported.
    // (Note: the test tolerates __malloc being absent from the export table;
    // it does NOT assert presence — that would be a separate positive test.)
    assert!(
        !exports.contains("__malloc") || {
            // If __malloc is present as a user function it means the test's
            // mir_program.functions contained it — which this test does not
            // arrange.  A false positive here would indicate a regression.
            eprintln!("WARNING: __malloc found in exports — may indicate over-export regression");
            false
        },
        "Internal helper '__malloc' must NOT be exported (it is not a user-defined function).\n\
         Actual exports: {:?}",
        exports
    );
}
