//! Android bridge generator
//!
//! Generates Kotlin files for running Clean Language WASM on Android.
//! Uses Android APIs: OkHttp, File, Log, etc.

/// Generate the CleanBridge.kt file for Android targets
pub fn generate_bridge_kt(wasm_filename: &str) -> String {
    format!(
        r#"// Auto-generated by Clean Language Compiler
// Target: Android
// WASM file: {wasm_filename}

package com.cleanlanguage.bridge

import android.content.Context
import android.util.Log
import java.io.File
import java.net.HttpURLConnection
import java.net.URL
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * CleanBridge - Runtime bridge for Clean Language WASM modules on Android
 *
 * This bridge provides native implementations of I/O operations that WASM
 * modules can call through the import mechanism.
 *
 * Note: This requires a WASM runtime like Wasmer-Android or Chicory.
 */
class CleanBridge(private val context: Context) {{

    companion object {{
        private const val TAG = "CleanBridge"
        private const val HEAP_START = 1024
    }}

    // Memory buffer representing WASM linear memory
    private var memory: ByteBuffer? = null
    private var heapPtr: Int = HEAP_START

    // Directory for file operations
    private val filesDir: File get() = context.filesDir

    // MARK: - Memory Management

    /**
     * Set the WASM memory buffer
     */
    fun setMemory(buffer: ByteBuffer) {{
        this.memory = buffer.order(ByteOrder.LITTLE_ENDIAN)
    }}

    /**
     * Allocate memory from the heap
     */
    fun malloc(size: Int): Int {{
        // Align to 8 bytes
        val aligned = (heapPtr + 7) and 7.inv()
        heapPtr = aligned + size
        return aligned
    }}

    // MARK: - String Operations

    /**
     * Read a string from WASM memory
     * String format: [length: i32 (4 bytes)][data: bytes...]
     */
    fun readString(ptr: Int): String {{
        val mem = memory ?: return ""
        if (ptr <= 0) return ""

        val length = mem.getInt(ptr)
        if (length <= 0) return ""

        val bytes = ByteArray(length)
        for (i in 0 until length) {{
            bytes[i] = mem.get(ptr + 4 + i)
        }}

        return String(bytes, Charsets.UTF_8)
    }}

    /**
     * Write a string to WASM memory
     */
    fun writeString(str: String): Int {{
        val mem = memory ?: return 0
        val bytes = str.toByteArray(Charsets.UTF_8)

        val ptr = malloc(bytes.size + 4)

        // Write length
        mem.putInt(ptr, bytes.size)

        // Write data
        for (i in bytes.indices) {{
            mem.put(ptr + 4 + i, bytes[i])
        }}

        return ptr
    }}

    // MARK: - Console I/O

    /**
     * Print text to logcat (no newline distinction in Android logging)
     */
    fun print(ptr: Int) {{
        val text = readString(ptr)
        Log.d(TAG, text)
    }}

    /**
     * Print text to logcat
     */
    fun printl(ptr: Int) {{
        val text = readString(ptr)
        Log.d(TAG, text)
    }}

    // MARK: - User Input
    // Note: Android doesn't have stdin. These return defaults.
    // For actual input, integrate with your UI layer.

    /**
     * Get string input (returns empty string - implement via UI)
     */
    fun input(promptPtr: Int): Int {{
        val prompt = readString(promptPtr)
        Log.d(TAG, "Input requested: $prompt")
        // In real implementation, show dialog and wait for result
        return writeString("")
    }}

    /**
     * Get integer input
     */
    fun inputInteger(promptPtr: Int): Int {{
        val prompt = readString(promptPtr)
        Log.d(TAG, "Integer input requested: $prompt")
        return 0
    }}

    /**
     * Get float input
     */
    fun inputFloat(promptPtr: Int): Double {{
        val prompt = readString(promptPtr)
        Log.d(TAG, "Float input requested: $prompt")
        return 0.0
    }}

    /**
     * Get yes/no input
     */
    fun inputYesNo(promptPtr: Int): Int {{
        val prompt = readString(promptPtr)
        Log.d(TAG, "Yes/No input requested: $prompt")
        return 0
    }}

    // MARK: - File Operations

    /**
     * Read file contents
     */
    fun fileRead(pathPtr: Int): Int {{
        val relativePath = readString(pathPtr)
        val file = File(filesDir, relativePath)

        return try {{
            val content = file.readText()
            writeString(content)
        }} catch (e: Exception) {{
            Log.e(TAG, "File read error: ${{e.message}}")
            0 // Return null pointer on error
        }}
    }}

    /**
     * Write content to file
     */
    fun fileWrite(pathPtr: Int, contentPtr: Int): Int {{
        val relativePath = readString(pathPtr)
        val content = readString(contentPtr)
        val file = File(filesDir, relativePath)

        return try {{
            // Create parent directories if needed
            file.parentFile?.mkdirs()
            file.writeText(content)
            1
        }} catch (e: Exception) {{
            Log.e(TAG, "File write error: ${{e.message}}")
            0
        }}
    }}

    /**
     * Check if file exists
     */
    fun fileExists(pathPtr: Int): Int {{
        val relativePath = readString(pathPtr)
        val file = File(filesDir, relativePath)
        return if (file.exists()) 1 else 0
    }}

    /**
     * Delete file
     */
    fun fileDelete(pathPtr: Int): Int {{
        val relativePath = readString(pathPtr)
        val file = File(filesDir, relativePath)

        return try {{
            if (file.delete()) 1 else 0
        }} catch (e: Exception) {{
            Log.e(TAG, "File delete error: ${{e.message}}")
            0
        }}
    }}

    // MARK: - HTTP Operations
    // Note: These use HttpURLConnection for simplicity.
    // Consider using OkHttp or Retrofit in production.

    /**
     * HTTP GET request (synchronous - call from background thread)
     */
    fun httpGet(urlPtr: Int): Int {{
        val urlString = readString(urlPtr)

        return try {{
            val url = URL(urlString)
            val connection = url.openConnection() as HttpURLConnection
            connection.requestMethod = "GET"
            connection.connectTimeout = 30000
            connection.readTimeout = 30000

            val content = connection.inputStream.bufferedReader().readText()
            connection.disconnect()

            writeString(content)
        }} catch (e: Exception) {{
            Log.e(TAG, "HTTP GET error: ${{e.message}}")
            0
        }}
    }}

    /**
     * HTTP POST request (synchronous - call from background thread)
     */
    fun httpPost(urlPtr: Int, bodyPtr: Int): Int {{
        val urlString = readString(urlPtr)
        val body = readString(bodyPtr)

        return try {{
            val url = URL(urlString)
            val connection = url.openConnection() as HttpURLConnection
            connection.requestMethod = "POST"
            connection.doOutput = true
            connection.setRequestProperty("Content-Type", "application/json")
            connection.connectTimeout = 30000
            connection.readTimeout = 30000

            connection.outputStream.bufferedWriter().use {{ it.write(body) }}

            val content = connection.inputStream.bufferedReader().readText()
            connection.disconnect()

            writeString(content)
        }} catch (e: Exception) {{
            Log.e(TAG, "HTTP POST error: ${{e.message}}")
            0
        }}
    }}

    /**
     * HTTP PUT request (synchronous - call from background thread)
     */
    fun httpPut(urlPtr: Int, bodyPtr: Int): Int {{
        val urlString = readString(urlPtr)
        val body = readString(bodyPtr)

        return try {{
            val url = URL(urlString)
            val connection = url.openConnection() as HttpURLConnection
            connection.requestMethod = "PUT"
            connection.doOutput = true
            connection.setRequestProperty("Content-Type", "application/json")
            connection.connectTimeout = 30000
            connection.readTimeout = 30000

            connection.outputStream.bufferedWriter().use {{ it.write(body) }}

            val content = connection.inputStream.bufferedReader().readText()
            connection.disconnect()

            writeString(content)
        }} catch (e: Exception) {{
            Log.e(TAG, "HTTP PUT error: ${{e.message}}")
            0
        }}
    }}

    /**
     * HTTP DELETE request (synchronous - call from background thread)
     */
    fun httpDelete(urlPtr: Int): Int {{
        val urlString = readString(urlPtr)

        return try {{
            val url = URL(urlString)
            val connection = url.openConnection() as HttpURLConnection
            connection.requestMethod = "DELETE"
            connection.connectTimeout = 30000
            connection.readTimeout = 30000

            val content = connection.inputStream.bufferedReader().readText()
            connection.disconnect()

            writeString(content)
        }} catch (e: Exception) {{
            Log.e(TAG, "HTTP DELETE error: ${{e.message}}")
            0
        }}
    }}
}}

/*
 * Usage Example with Wasmer-Android or similar:
 *
 * class MainActivity : AppCompatActivity() {{
 *     private lateinit var bridge: CleanBridge
 *
 *     override fun onCreate(savedInstanceState: Bundle?) {{
 *         super.onCreate(savedInstanceState)
 *
 *         bridge = CleanBridge(this)
 *
 *         // Load WASM file from assets
 *         val wasmBytes = assets.open("{wasm_filename}").readBytes()
 *
 *         // Create WASM instance with imports pointing to bridge methods
 *         // The exact API depends on your WASM runtime
 *
 *         // Set memory buffer
 *         bridge.setMemory(wasmMemoryBuffer)
 *
 *         // Call start function on background thread
 *         lifecycleScope.launch(Dispatchers.IO) {{
 *             wasmInstance.exports._start()
 *         }}
 *     }}
 * }}
 */
"#
    )
}
