//! Browser bridge generator
//!
//! Generates JavaScript files for running Clean Language WASM in browsers.
//! Uses web APIs: fetch, localStorage, console.

/// Generate the main bridge.js file for browser targets
pub fn generate_bridge_js(wasm_filename: &str) -> String {
    format!(
        r#"// Auto-generated by Clean Language Compiler
// Target: browser
// WASM file: {wasm_filename}

/**
 * CleanBridge - Runtime bridge for Clean Language WASM modules in browsers
 *
 * Provides implementations for:
 * - Console I/O (print, printl)
 * - User input (via window.prompt)
 * - File operations (via localStorage)
 * - HTTP operations (via fetch API)
 */
export class CleanBridge {{
  constructor(memory) {{
    this.memory = memory;
    this.decoder = new TextDecoder('utf-8');
    this.encoder = new TextEncoder();
  }}

  /**
   * Read a Clean Language string from WASM memory
   * String format: [length: i32 (4 bytes)][data: bytes...]
   */
  readString(ptr) {{
    if (ptr === 0) return '';
    const view = new DataView(this.memory.buffer);
    const length = view.getInt32(ptr, true); // little-endian
    if (length <= 0) return '';
    const bytes = new Uint8Array(this.memory.buffer, ptr + 4, length);
    return this.decoder.decode(bytes);
  }}

  /**
   * Write a JavaScript string to WASM memory
   * Returns pointer to the new string
   */
  writeString(str, allocFn) {{
    const bytes = this.encoder.encode(str);
    const ptr = allocFn(bytes.length + 4); // 4 bytes for length prefix
    const view = new DataView(this.memory.buffer);
    view.setInt32(ptr, bytes.length, true); // little-endian
    new Uint8Array(this.memory.buffer, ptr + 4, bytes.length).set(bytes);
    return ptr;
  }}

  /**
   * Get the import object for WASM instantiation
   */
  getImports(allocFn) {{
    const self = this;

    return {{
      env: {{
        // Console I/O
        print: (ptr) => {{
          const text = self.readString(ptr);
          console.log(text);
        }},

        printl: (ptr) => {{
          const text = self.readString(ptr);
          console.log(text);
        }},

        // User input (browser prompt)
        input: (promptPtr) => {{
          const prompt = self.readString(promptPtr);
          const result = window.prompt(prompt) || '';
          return self.writeString(result, allocFn);
        }},

        input_integer: (promptPtr) => {{
          const prompt = self.readString(promptPtr);
          const result = window.prompt(prompt) || '0';
          return parseInt(result, 10) || 0;
        }},

        input_float: (promptPtr) => {{
          const prompt = self.readString(promptPtr);
          const result = window.prompt(prompt) || '0';
          return parseFloat(result) || 0.0;
        }},

        input_yesno: (promptPtr) => {{
          const prompt = self.readString(promptPtr);
          const result = window.prompt(prompt + ' (yes/no)') || 'no';
          return result.toLowerCase().startsWith('y') ? 1 : 0;
        }},

        // File operations (localStorage-based)
        file_read: (pathPtr) => {{
          const path = self.readString(pathPtr);
          const content = localStorage.getItem(`clean:${{path}}`);
          if (content === null) return 0;
          return self.writeString(content, allocFn);
        }},

        file_write: (pathPtr, contentPtr) => {{
          const path = self.readString(pathPtr);
          const content = self.readString(contentPtr);
          try {{
            localStorage.setItem(`clean:${{path}}`, content);
            return 1;
          }} catch (e) {{
            console.error('File write error:', e);
            return 0;
          }}
        }},

        file_exists: (pathPtr) => {{
          const path = self.readString(pathPtr);
          return localStorage.getItem(`clean:${{path}}`) !== null ? 1 : 0;
        }},

        file_delete: (pathPtr) => {{
          const path = self.readString(pathPtr);
          localStorage.removeItem(`clean:${{path}}`);
          return 1;
        }},

        // HTTP operations (fetch-based)
        http_get: (urlPtr) => {{
          // Note: This is synchronous for WASM compatibility
          // In practice, you may need async handling
          const url = self.readString(urlPtr);
          console.warn('http_get in browser is limited - consider async patterns');
          return 0; // Return empty for sync context
        }},

        http_post: (urlPtr, bodyPtr) => {{
          const url = self.readString(urlPtr);
          const body = self.readString(bodyPtr);
          console.warn('http_post in browser is limited - consider async patterns');
          return 0;
        }},

        http_put: (urlPtr, bodyPtr) => {{
          const url = self.readString(urlPtr);
          const body = self.readString(bodyPtr);
          console.warn('http_put in browser is limited - consider async patterns');
          return 0;
        }},

        http_delete: (urlPtr) => {{
          const url = self.readString(urlPtr);
          console.warn('http_delete in browser is limited - consider async patterns');
          return 0;
        }},

        // Memory operations (if needed by runtime)
        memory_copy: (dest, src, len) => {{
          const destArray = new Uint8Array(self.memory.buffer, dest, len);
          const srcArray = new Uint8Array(self.memory.buffer, src, len);
          destArray.set(srcArray);
        }}
      }}
    }};
  }}

  /**
   * Async HTTP methods for proper browser usage
   */
  async httpGet(url) {{
    const response = await fetch(url);
    return await response.text();
  }}

  async httpPost(url, body, contentType = 'application/json') {{
    const response = await fetch(url, {{
      method: 'POST',
      headers: {{ 'Content-Type': contentType }},
      body: body
    }});
    return await response.text();
  }}

  async httpPut(url, body, contentType = 'application/json') {{
    const response = await fetch(url, {{
      method: 'PUT',
      headers: {{ 'Content-Type': contentType }},
      body: body
    }});
    return await response.text();
  }}

  async httpDelete(url) {{
    const response = await fetch(url, {{ method: 'DELETE' }});
    return await response.text();
  }}
}}

export default CleanBridge;
"#
    )
}

/// Generate the loader.js file for easy WASM loading in browsers
pub fn generate_loader_js(wasm_filename: &str) -> String {
    format!(
        r#"// Auto-generated by Clean Language Compiler
// Target: browser
// WASM file: {wasm_filename}

import {{ CleanBridge }} from './bridge.js';

/**
 * Load and run a Clean Language WASM module
 */
export async function loadCleanModule(wasmPath = './{wasm_filename}') {{
  // Fetch and compile the WASM module
  const response = await fetch(wasmPath);
  const wasmBytes = await response.arrayBuffer();

  // Create memory (1 page = 64KB, allow growth to 1024 pages = 64MB)
  const memory = new WebAssembly.Memory({{ initial: 1, maximum: 1024 }});

  // Create bridge
  const bridge = new CleanBridge(memory);

  // Track heap pointer for allocation
  let heapPtr = 1024; // HEAP_START

  function malloc(size) {{
    // Align to 8 bytes
    const aligned = (heapPtr + 7) & ~7;
    heapPtr = aligned + size;
    return aligned;
  }}

  // Get imports with allocator
  const imports = bridge.getImports(malloc);
  imports.env.memory = memory;

  // Instantiate the module
  const {{ instance }} = await WebAssembly.instantiate(wasmBytes, imports);

  // Run the start function if it exists
  if (instance.exports._start) {{
    instance.exports._start();
  }} else if (instance.exports.start) {{
    instance.exports.start();
  }} else if (instance.exports.main) {{
    instance.exports.main();
  }}

  return {{
    instance,
    memory,
    bridge,
    exports: instance.exports
  }};
}}

/**
 * Simple runner - loads and executes the WASM
 */
export async function run() {{
  try {{
    const module = await loadCleanModule();
    console.log('Clean Language module loaded successfully');
    return module;
  }} catch (error) {{
    console.error('Failed to load Clean Language module:', error);
    throw error;
  }}
}}

// Auto-run if this is the main module
if (typeof document !== 'undefined') {{
  document.addEventListener('DOMContentLoaded', () => {{
    run().catch(console.error);
  }});
}}

export default {{ loadCleanModule, run }};
"#
    )
}
