//! iOS/macOS bridge generator
//!
//! Generates Swift files for running Clean Language WASM on Apple platforms.
//! Uses Foundation APIs: URLSession, FileManager, etc.

/// Generate the CleanBridge.swift file for iOS/macOS targets
pub fn generate_bridge_swift(wasm_filename: &str) -> String {
    format!(
        r#"// Auto-generated by Clean Language Compiler
// Target: iOS/macOS
// WASM file: {wasm_filename}

import Foundation
import JavaScriptCore

/**
 * CleanBridge - Runtime bridge for Clean Language WASM modules on Apple platforms
 *
 * This bridge provides native implementations of I/O operations that WASM
 * modules can call through the import mechanism.
 *
 * Note: This requires a WASM runtime like WasmKit or JavaScriptCore's WASM support.
 */
public class CleanBridge {{

    // MARK: - Properties

    private var memory: UnsafeMutableRawPointer?
    private var memorySize: Int = 0
    private var heapPtr: Int32 = 1024 // HEAP_START

    // Document directory for file operations
    private let documentsPath: URL

    // MARK: - Initialization

    public init() {{
        // Get documents directory
        let paths = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
        documentsPath = paths[0].appendingPathComponent("CleanLanguage")

        // Create directory if needed
        try? FileManager.default.createDirectory(at: documentsPath, withIntermediateDirectories: true)
    }}

    // MARK: - Memory Management

    /// Set the WASM memory buffer
    public func setMemory(_ ptr: UnsafeMutableRawPointer, size: Int) {{
        self.memory = ptr
        self.memorySize = size
    }}

    /// Allocate memory from the heap
    public func malloc(size: Int32) -> Int32 {{
        // Align to 8 bytes
        let aligned = (heapPtr + 7) & ~7
        heapPtr = aligned + size
        return aligned
    }}

    // MARK: - String Operations

    /// Read a string from WASM memory
    /// String format: [length: i32 (4 bytes)][data: bytes...]
    public func readString(ptr: Int32) -> String {{
        guard let memory = memory, ptr > 0 else {{ return "" }}

        let basePtr = memory.advanced(by: Int(ptr))
        let length = basePtr.load(as: Int32.self)

        guard length > 0 else {{ return "" }}

        let dataPtr = basePtr.advanced(by: 4)
        let data = Data(bytes: dataPtr, count: Int(length))

        return String(data: data, encoding: .utf8) ?? ""
    }}

    /// Write a string to WASM memory
    public func writeString(_ str: String) -> Int32 {{
        guard let memory = memory else {{ return 0 }}
        guard let data = str.data(using: .utf8) else {{ return 0 }}

        let ptr = malloc(size: Int32(data.count + 4))
        let basePtr = memory.advanced(by: Int(ptr))

        // Write length
        basePtr.storeBytes(of: Int32(data.count), as: Int32.self)

        // Write data
        let dataPtr = basePtr.advanced(by: 4)
        data.copyBytes(to: dataPtr.assumingMemoryBound(to: UInt8.self), count: data.count)

        return ptr
    }}

    // MARK: - Console I/O

    /// Print text to console (no newline)
    public func print(ptr: Int32) {{
        let text = readString(ptr: ptr)
        Swift.print(text, terminator: "")
    }}

    /// Print text to console with newline
    public func printl(ptr: Int32) {{
        let text = readString(ptr: ptr)
        Swift.print(text)
    }}

    // MARK: - User Input

    /// Get string input from user (iOS: returns empty, macOS: uses stdin)
    public func input(promptPtr: Int32) -> Int32 {{
        let prompt = readString(ptr: promptPtr)
        Swift.print(prompt, terminator: "")

        #if os(macOS)
        if let line = readLine() {{
            return writeString(line)
        }}
        #endif

        return writeString("")
    }}

    /// Get integer input from user
    public func inputInteger(promptPtr: Int32) -> Int32 {{
        let prompt = readString(ptr: promptPtr)
        Swift.print(prompt, terminator: "")

        #if os(macOS)
        if let line = readLine(), let value = Int32(line) {{
            return value
        }}
        #endif

        return 0
    }}

    /// Get float input from user
    public func inputFloat(promptPtr: Int32) -> Double {{
        let prompt = readString(ptr: promptPtr)
        Swift.print(prompt, terminator: "")

        #if os(macOS)
        if let line = readLine(), let value = Double(line) {{
            return value
        }}
        #endif

        return 0.0
    }}

    /// Get yes/no input from user
    public func inputYesNo(promptPtr: Int32) -> Int32 {{
        let prompt = readString(ptr: promptPtr)
        Swift.print("\(prompt) (yes/no): ", terminator: "")

        #if os(macOS)
        if let line = readLine() {{
            return line.lowercased().hasPrefix("y") ? 1 : 0
        }}
        #endif

        return 0
    }}

    // MARK: - File Operations

    /// Read file contents
    public func fileRead(pathPtr: Int32) -> Int32 {{
        let relativePath = readString(ptr: pathPtr)
        let fileURL = documentsPath.appendingPathComponent(relativePath)

        do {{
            let content = try String(contentsOf: fileURL, encoding: .utf8)
            return writeString(content)
        }} catch {{
            return 0 // Return null pointer on error
        }}
    }}

    /// Write content to file
    public func fileWrite(pathPtr: Int32, contentPtr: Int32) -> Int32 {{
        let relativePath = readString(ptr: pathPtr)
        let content = readString(ptr: contentPtr)
        let fileURL = documentsPath.appendingPathComponent(relativePath)

        do {{
            // Create parent directory if needed
            let directory = fileURL.deletingLastPathComponent()
            try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)

            try content.write(to: fileURL, atomically: true, encoding: .utf8)
            return 1
        }} catch {{
            return 0
        }}
    }}

    /// Check if file exists
    public func fileExists(pathPtr: Int32) -> Int32 {{
        let relativePath = readString(ptr: pathPtr)
        let fileURL = documentsPath.appendingPathComponent(relativePath)
        return FileManager.default.fileExists(atPath: fileURL.path) ? 1 : 0
    }}

    /// Delete file
    public func fileDelete(pathPtr: Int32) -> Int32 {{
        let relativePath = readString(ptr: pathPtr)
        let fileURL = documentsPath.appendingPathComponent(relativePath)

        do {{
            try FileManager.default.removeItem(at: fileURL)
            return 1
        }} catch {{
            return 0
        }}
    }}

    // MARK: - HTTP Operations

    /// HTTP GET request (synchronous)
    public func httpGet(urlPtr: Int32) -> Int32 {{
        let urlString = readString(ptr: urlPtr)
        guard let url = URL(string: urlString) else {{ return 0 }}

        var result: Int32 = 0
        let semaphore = DispatchSemaphore(value: 0)

        let task = URLSession.shared.dataTask(with: url) {{ data, response, error in
            defer {{ semaphore.signal() }}

            guard let data = data, error == nil else {{ return }}
            if let content = String(data: data, encoding: .utf8) {{
                result = self.writeString(content)
            }}
        }}
        task.resume()
        semaphore.wait()

        return result
    }}

    /// HTTP POST request (synchronous)
    public func httpPost(urlPtr: Int32, bodyPtr: Int32) -> Int32 {{
        let urlString = readString(ptr: urlPtr)
        let body = readString(ptr: bodyPtr)
        guard let url = URL(string: urlString) else {{ return 0 }}

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.httpBody = body.data(using: .utf8)
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")

        var result: Int32 = 0
        let semaphore = DispatchSemaphore(value: 0)

        let task = URLSession.shared.dataTask(with: request) {{ data, response, error in
            defer {{ semaphore.signal() }}

            guard let data = data, error == nil else {{ return }}
            if let content = String(data: data, encoding: .utf8) {{
                result = self.writeString(content)
            }}
        }}
        task.resume()
        semaphore.wait()

        return result
    }}

    /// HTTP PUT request (synchronous)
    public func httpPut(urlPtr: Int32, bodyPtr: Int32) -> Int32 {{
        let urlString = readString(ptr: urlPtr)
        let body = readString(ptr: bodyPtr)
        guard let url = URL(string: urlString) else {{ return 0 }}

        var request = URLRequest(url: url)
        request.httpMethod = "PUT"
        request.httpBody = body.data(using: .utf8)
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")

        var result: Int32 = 0
        let semaphore = DispatchSemaphore(value: 0)

        let task = URLSession.shared.dataTask(with: request) {{ data, response, error in
            defer {{ semaphore.signal() }}

            guard let data = data, error == nil else {{ return }}
            if let content = String(data: data, encoding: .utf8) {{
                result = self.writeString(content)
            }}
        }}
        task.resume()
        semaphore.wait()

        return result
    }}

    /// HTTP DELETE request (synchronous)
    public func httpDelete(urlPtr: Int32) -> Int32 {{
        let urlString = readString(ptr: urlPtr)
        guard let url = URL(string: urlString) else {{ return 0 }}

        var request = URLRequest(url: url)
        request.httpMethod = "DELETE"

        var result: Int32 = 0
        let semaphore = DispatchSemaphore(value: 0)

        let task = URLSession.shared.dataTask(with: request) {{ data, response, error in
            defer {{ semaphore.signal() }}

            guard let data = data, error == nil else {{ return }}
            if let content = String(data: data, encoding: .utf8) {{
                result = self.writeString(content)
            }}
        }}
        task.resume()
        semaphore.wait()

        return result
    }}
}}

// MARK: - Usage Example

/*
 Usage with WasmKit or similar WASM runtime:

 let bridge = CleanBridge()

 // Load WASM file
 let wasmData = try Data(contentsOf: Bundle.main.url(forResource: "{wasm_filename}", withExtension: nil)!)

 // Create WASM instance with imports pointing to bridge methods
 // The exact API depends on your WASM runtime

 // Set memory
 bridge.setMemory(wasmMemoryPointer, size: wasmMemorySize)

 // Call start function
 wasmInstance.exports._start()
 */
"#
    )
}
