//! Node.js bridge generator
//!
//! Generates JavaScript/ESM files for running Clean Language WASM in Node.js.
//! Uses Node APIs: fs, http/https, process, readline.

/// Generate the main bridge.mjs file for Node.js targets
pub fn generate_bridge_mjs(wasm_filename: &str) -> String {
    format!(
        r#"// Auto-generated by Clean Language Compiler
// Target: Node.js
// WASM file: {wasm_filename}

import * as fs from 'fs';
import * as path from 'path';
import * as https from 'https';
import * as http from 'http';
import * as readline from 'readline';

/**
 * CleanBridge - Runtime bridge for Clean Language WASM modules in Node.js
 *
 * Provides implementations for:
 * - Console I/O (print, printl)
 * - User input (via readline)
 * - File operations (via fs module)
 * - HTTP operations (via http/https modules)
 */
export class CleanBridge {{
  constructor(memory) {{
    this.memory = memory;
    this.decoder = new TextDecoder('utf-8');
    this.encoder = new TextEncoder();
    this.rl = null;
  }}

  /**
   * Read a Clean Language string from WASM memory
   * String format: [length: i32 (4 bytes)][data: bytes...]
   */
  readString(ptr) {{
    if (ptr === 0) return '';
    const view = new DataView(this.memory.buffer);
    const length = view.getInt32(ptr, true); // little-endian
    if (length <= 0) return '';
    const bytes = new Uint8Array(this.memory.buffer, ptr + 4, length);
    return this.decoder.decode(bytes);
  }}

  /**
   * Write a JavaScript string to WASM memory
   * Returns pointer to the new string
   */
  writeString(str, allocFn) {{
    const bytes = this.encoder.encode(str);
    const ptr = allocFn(bytes.length + 4); // 4 bytes for length prefix
    const view = new DataView(this.memory.buffer);
    view.setInt32(ptr, bytes.length, true); // little-endian
    new Uint8Array(this.memory.buffer, ptr + 4, bytes.length).set(bytes);
    return ptr;
  }}

  /**
   * Initialize readline interface for user input
   */
  initReadline() {{
    if (!this.rl) {{
      this.rl = readline.createInterface({{
        input: process.stdin,
        output: process.stdout
      }});
    }}
    return this.rl;
  }}

  /**
   * Close readline interface
   */
  closeReadline() {{
    if (this.rl) {{
      this.rl.close();
      this.rl = null;
    }}
  }}

  /**
   * Synchronous input (using sync-prompt pattern)
   */
  inputSync(prompt) {{
    // For synchronous input in Node.js, we use a workaround
    const buffer = Buffer.alloc(1024);
    process.stdout.write(prompt);

    try {{
      const fd = fs.openSync('/dev/stdin', 'rs');
      const bytesRead = fs.readSync(fd, buffer, 0, buffer.length, null);
      fs.closeSync(fd);
      return buffer.toString('utf8', 0, bytesRead).trim();
    }} catch (e) {{
      // Fallback for Windows or when /dev/stdin is unavailable
      return '';
    }}
  }}

  /**
   * Get the import object for WASM instantiation
   */
  getImports(allocFn) {{
    const self = this;

    return {{
      env: {{
        // Console I/O
        print: (ptr) => {{
          const text = self.readString(ptr);
          process.stdout.write(text);
        }},

        printl: (ptr) => {{
          const text = self.readString(ptr);
          console.log(text);
        }},

        // User input
        input: (promptPtr) => {{
          const prompt = self.readString(promptPtr);
          const result = self.inputSync(prompt);
          return self.writeString(result, allocFn);
        }},

        input_integer: (promptPtr) => {{
          const prompt = self.readString(promptPtr);
          const result = self.inputSync(prompt);
          return parseInt(result, 10) || 0;
        }},

        input_float: (promptPtr) => {{
          const prompt = self.readString(promptPtr);
          const result = self.inputSync(prompt);
          return parseFloat(result) || 0.0;
        }},

        input_yesno: (promptPtr) => {{
          const prompt = self.readString(promptPtr);
          const result = self.inputSync(prompt + ' (yes/no): ');
          return result.toLowerCase().startsWith('y') ? 1 : 0;
        }},

        // File operations
        file_read: (pathPtr) => {{
          const filePath = self.readString(pathPtr);
          try {{
            const content = fs.readFileSync(filePath, 'utf8');
            return self.writeString(content, allocFn);
          }} catch (e) {{
            return 0; // Return null pointer on error
          }}
        }},

        file_write: (pathPtr, contentPtr) => {{
          const filePath = self.readString(pathPtr);
          const content = self.readString(contentPtr);
          try {{
            // Ensure directory exists
            const dir = path.dirname(filePath);
            if (dir && !fs.existsSync(dir)) {{
              fs.mkdirSync(dir, {{ recursive: true }});
            }}
            fs.writeFileSync(filePath, content, 'utf8');
            return 1;
          }} catch (e) {{
            console.error('File write error:', e.message);
            return 0;
          }}
        }},

        file_exists: (pathPtr) => {{
          const filePath = self.readString(pathPtr);
          return fs.existsSync(filePath) ? 1 : 0;
        }},

        file_delete: (pathPtr) => {{
          const filePath = self.readString(pathPtr);
          try {{
            fs.unlinkSync(filePath);
            return 1;
          }} catch (e) {{
            return 0;
          }}
        }},

        // HTTP operations (synchronous wrappers)
        http_get: (urlPtr) => {{
          // Note: Synchronous HTTP is not recommended in Node.js
          // This is a simplified implementation
          console.warn('Synchronous http_get - consider async patterns');
          return 0;
        }},

        http_post: (urlPtr, bodyPtr) => {{
          console.warn('Synchronous http_post - consider async patterns');
          return 0;
        }},

        http_put: (urlPtr, bodyPtr) => {{
          console.warn('Synchronous http_put - consider async patterns');
          return 0;
        }},

        http_delete: (urlPtr) => {{
          console.warn('Synchronous http_delete - consider async patterns');
          return 0;
        }},

        // Memory operations
        memory_copy: (dest, src, len) => {{
          const destArray = new Uint8Array(self.memory.buffer, dest, len);
          const srcArray = new Uint8Array(self.memory.buffer, src, len);
          destArray.set(srcArray);
        }}
      }}
    }};
  }}

  /**
   * Async HTTP GET
   */
  httpGet(url) {{
    return new Promise((resolve, reject) => {{
      const client = url.startsWith('https') ? https : http;
      client.get(url, (res) => {{
        let data = '';
        res.on('data', chunk => data += chunk);
        res.on('end', () => resolve(data));
      }}).on('error', reject);
    }});
  }}

  /**
   * Async HTTP POST
   */
  httpPost(url, body, contentType = 'application/json') {{
    return new Promise((resolve, reject) => {{
      const urlObj = new URL(url);
      const client = urlObj.protocol === 'https:' ? https : http;

      const options = {{
        hostname: urlObj.hostname,
        port: urlObj.port,
        path: urlObj.pathname + urlObj.search,
        method: 'POST',
        headers: {{
          'Content-Type': contentType,
          'Content-Length': Buffer.byteLength(body)
        }}
      }};

      const req = client.request(options, (res) => {{
        let data = '';
        res.on('data', chunk => data += chunk);
        res.on('end', () => resolve(data));
      }});

      req.on('error', reject);
      req.write(body);
      req.end();
    }});
  }}
}}

export default CleanBridge;
"#
    )
}

/// Generate the run.mjs file for easy execution in Node.js
pub fn generate_run_mjs(wasm_filename: &str) -> String {
    format!(
        r#"#!/usr/bin/env node
// Auto-generated by Clean Language Compiler
// Target: Node.js
// WASM file: {wasm_filename}

import * as fs from 'fs';
import * as path from 'path';
import {{ fileURLToPath }} from 'url';
import {{ CleanBridge }} from './bridge.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Load and run a Clean Language WASM module in Node.js
 */
export async function loadCleanModule(wasmPath) {{
  // Default to the generated WASM file
  if (!wasmPath) {{
    wasmPath = path.join(__dirname, '{wasm_filename}');
  }}

  // Read WASM file
  const wasmBytes = fs.readFileSync(wasmPath);

  // Create memory (1 page = 64KB, allow growth to 1024 pages = 64MB)
  const memory = new WebAssembly.Memory({{ initial: 1, maximum: 1024 }});

  // Create bridge
  const bridge = new CleanBridge(memory);

  // Track heap pointer for allocation
  let heapPtr = 1024; // HEAP_START

  function malloc(size) {{
    // Align to 8 bytes
    const aligned = (heapPtr + 7) & ~7;
    heapPtr = aligned + size;
    return aligned;
  }}

  // Get imports with allocator
  const imports = bridge.getImports(malloc);
  imports.env.memory = memory;

  // Instantiate the module
  const {{ instance }} = await WebAssembly.instantiate(wasmBytes, imports);

  return {{
    instance,
    memory,
    bridge,
    exports: instance.exports,
    run: () => {{
      // Run the start function if it exists
      if (instance.exports._start) {{
        return instance.exports._start();
      }} else if (instance.exports.start) {{
        return instance.exports.start();
      }} else if (instance.exports.main) {{
        return instance.exports.main();
      }}
    }}
  }};
}}

/**
 * Main entry point
 */
async function main() {{
  const args = process.argv.slice(2);
  const wasmPath = args[0] || path.join(__dirname, '{wasm_filename}');

  try {{
    const module = await loadCleanModule(wasmPath);
    const result = module.run();

    // Clean up
    module.bridge.closeReadline();

    // Exit with result if it's a number
    if (typeof result === 'number') {{
      process.exit(result);
    }}
  }} catch (error) {{
    console.error('Error running Clean Language module:', error);
    process.exit(1);
  }}
}}

// Run if this is the main module
main();

export default {{ loadCleanModule }};
"#
    )
}
